python -m ct_simulator.run_tracing ^
    --exp_id "win_0/" ^
    --netsize 100 ^
    --k 10 ^
    --multip 0 ^
    --model "covid" ^
    --dual 1 ^
    --overlap .8 ^
    --nnets 1 ^
    --niters 1 ^
    --separate_traced False ^
    --seed 32 ^
    --netseed 11 ^
    --taut .1 ^
    --taur .005 ^
    --animate 0 ^
    --summary_print 3