name: control
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - conda
  - matplotlib
  - numpy
  - networkx
  - scipy
  - tqdm
  - dill
  - pandas
  - ipython
  - pygraphviz
  - plotly
  - pyvis
  - imageio
  - jupyterlab
  - scikit-learn
  - pytorch
  - pytorch-cuda=12.1
  - pytorch-sparse
  - pytorch-scatter
  - pyg